services:
  glances:
    container_name: glances
    environment:
      - "GLANCES_OPT=-w"
    hostname: ${HOSTNAME}
    image: nicolargo/glances:latest-full
    pid: host
    ports:
      - 61208:61208
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock